apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: todo-flask
        image: td2478/todo-flask:v4
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: mongo-service
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
