apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer # Use LoadBalancer for external access (minikube assigns ClusterIP by default)
